site_name: Lumi's Blog
site_url: https://bhaaa-zlm.github.io/
site_author: Lumi
site_description: Lumi's Blog

repo_url: https://github.com/BHAAA-ZLM/BHAAA-ZLM.github.io
repo_name: BHAAA-ZLM.github.io

copyright: Copyright &copy; 2022 Lumi

extra: 
  social:
    - icon: fontawesome/brands/bilibili
    - icon: fontawesome/brands/github

theme:

  font: 
    text: Lobster

  extra_css:
    - stylesheets/extra.css
    - https://fonts.googleapis.com/css2?family=Bangers&display=swap

  logo: assets/image/fatLogo.png

  favicon: assets/image/fatLogo.png

  name: material

  features: 
    - navigation.tabs
    - navigation.expand
    - navigation.top
    - navigation.expand
    - navigation.indexes
    - search.suggest
    - search.highlight

  palette: 
    # Palette toggle for light mode
    - scheme: default
      primary: red
      ccent: pink
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: red
      accent: pink
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  
nav:
  - Life:
    - Life/index.md
  - Biology:
    - Biology/index.md
  - CS:
    - CS/index.md
    - Projects: CS/Projects/Projects.md
  - Learning:
    - Learning/index.md
    - Chemistry:
      - Chemistry Experiments: Learning/Chemistry/Experiments.md

  